# Generated by Django 6.0 on 2025-12-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offer', 'Offer')], default='Applied', max_length=20)),
                ('applied_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
